### ISSUE TITLE
Uncaught ReferenceError: process is not defined 

### ISSUE THREAD

**Issue by abacai** [moznion/crx-table-to-spreadsheet#1]
there are a few places where you assume process is defined.  All of the lines are of the form

```
if (process.env.NODE_ENV === "test") {
```

I think you need to check if process is defined first:

```
if(typeof process !== 'undefined' && process.env && process.env.NODE_ENV === 'test') {
```

**Comment by moznion** [comment]
Thank you for your suggestion.
I've just applied this improvement and released :beer:
